# AI Chat Configuration
ai:
  openai:
    # API key will be read from environment variable OPENAI_API_KEY
    api-key: ${OPENAI_API_KEY}
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    model: ${OPENAI_MODEL:gpt-3.5-turbo}
    temperature: 0.7
    max-tokens: 2000

# MCP Function Calling Configuration
mcp:
  enabled: true
  functions:
    - getCurrentTime
    - calculate
    - generateRandomNumber
    - getWeather
    - analyzeText
    - translate
    - generateUUID
    - formatString
